# Generated by Django 4.2.2 on 2023-06-23 08:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMailingSubscribe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
            ],
            options={
                "verbose_name": "UserSubscribe",
                "verbose_name_plural": "UsersSubscribes",
                "db_table": "user_mailing_subscribe",
            },
        ),
    ]
