@startuml ugc-watch-film
== Старт просмотра ==
autonumber
activate WebClient
database Kafka
WebClient -> Service: POST watch/<UUID:film_id>
activate Service
alt #LightBlue Просмотр разрешен
    database Kafka
    Service -> WebClient: Запрос удовлетворен
    activate Kafka
    Service -> Kafka: Запись события
    Kafka --> Service: Записано
else #Pink Пользователь не имеет доступ к фильму
    Service -> WebClient: Запрос отклонен
end
deactivate Kafka
deactivate Service

== Дальнейший просмотр ==
WebClient -> Service: Новые данные о просмотре
activate Service
activate Kafka
Service -> Kafka: Запись события
database Redis
alt Пользователь перестал смотреть фильм
    activate ETL
    database ClickHouse
    ETL -> Kafka: Запрос данных
    Kafka -> ETL: Отдача данных
    deactivate Kafka
    ETL -> ETL: Трансформация данных
    activate ClickHouse
    ETL -> ClickHouse: Запись в ClickHouse
    ClickHouse --> ETL: Успешно
    deactivate ClickHouse
    ETL --> Service: ETL процесс окончен
    Service -> Redis: Запись последнего времени
    deactivate ETL
end
@enduml