@startuml ugc-watch-film
== Старт просмотра ==
autonumber
activate WebClient
WebClient -> Service: POST watch/<UUID:film_id>
activate Service
database Redis
database Kafka
alt #LightBlue Просмотр разрешен
    database Kafka
    activate Kafka
    Service -> Kafka: Запись события
    Kafka --> Service: Записано
    Service -> WebClient: Запрос удовлетворен
    Service -> Redis: Запись данных
    Redis --> Service: Записано
else #Pink Пользователь не имеет доступ к фильму
    Service -> WebClient: Запрос отклонен
end
deactivate Kafka
deactivate Service

== Дальнейший просмотр ==
WebClient -> Service: Новые данные о просмотре
activate Service
activate Kafka
Service -> Kafka: Запись события
Kafka --> Service: Записано
activate ETL
database ClickHouse
ETL -> Kafka: Запрос данных
Kafka -> ETL: Отдача данных
deactivate Kafka
ETL -> ETL: Трансформация данных
activate ClickHouse
ETL -> ClickHouse: Запись в ClickHouse
ClickHouse --> ETL: Успешно
deactivate ClickHouse
Service -> Redis: Перезапись последних данных
Redis --> Service: Записано
deactivate ETL
@enduml