"""Change Field

Revision ID: 135c771212e9
Revises: a0e2fccc2684
Create Date: 2023-07-17 16:29:14.500537

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "135c771212e9"
down_revision = "a0e2fccc2684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("currency", sa.String(), nullable=False))
    op.drop_column("transactions", "ttl")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("ttl", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("transactions", "currency")
    # ### end Alembic commands ###
