"""Add unique constraint

Revision ID: 69c81d942555
Revises: e0c5406a10e6
Create Date: 2023-07-18 13:33:58.677257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "69c81d942555"
down_revision = "e0c5406a10e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("payment_details", postgresql.JSON(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "payment_details")
    # ### end Alembic commands ###
