"""Initial

Revision ID: 7cf1b17f3fea
Revises:
Create Date: 2023-07-16 16:04:34.940504

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cf1b17f3fea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions_tiers",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subscribe_id", sa.UUID(), nullable=False),
        sa.Column("duratation", sa.DateTime(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("discount_duratation", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("subscribe_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("ttl", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column(
            "operate_status",
            sa.Enum("waiting", "success", "error", "canceled", name="operatestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("subscriptions_tiers")
    # ### end Alembic commands ###
