"""Rename ID

Revision ID: bb42c3e7e8e4
Revises: 7cf1b17f3fea
Create Date: 2023-07-16 17:32:52.936867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb42c3e7e8e4"
down_revision = "7cf1b17f3fea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions_tiers", sa.Column("id", sa.UUID(), nullable=False))
    op.drop_column("subscriptions_tiers", "subscribe_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions_tiers",
        sa.Column("subscribe_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_column("subscriptions_tiers", "id")
    # ### end Alembic commands ###
