"""Add unique constraint

Revision ID: e0c5406a10e6
Revises: 135c771212e9
Create Date: 2023-07-17 17:17:02.768561

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "e0c5406a10e6"
down_revision = "135c771212e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "transactions", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="unique")
    # ### end Alembic commands ###
