[tool.black]
line-length=100
exclude = '''
(
  /(
    | __pycache__
    | venv
  )/
)
'''

[tool.isort]
src_paths=["src", "tests"]
extend_skip=["wsgi_app.py"]
profile="black"
multi_line_output=1
line_length=100