@startuml
title Subscription auto-renewal

skinparam participant {
    BackgroundColor LightBlue
}

participant "Scheduler" as scheduler
participant "PostgreSQL" as postgres
participant "Payment Provider" as provider
participant "Notifications_API" as notifications
participant "Auth_API" as auth

activate scheduler
activate postgres
scheduler -> postgres: Получение истекших подписок
postgres --> scheduler: list[dict] ответ
opt auto-renewal=True
    activate provider
    scheduler -> provider: Отправка запроса на оплату
    alt Ошибка при оплате
        provider --> scheduler: Ответ с ошибкой оплаты
        scheduler -> postgres: Записать лог не успешной транзакции
        activate auth
        scheduler -> auth: Изменение роли пользователя на Default
        activate notifications
        scheduler -> notifications: Уведомление об ошибке автопродления
    else Успешная оплата
        provider --> scheduler: Ответ об успешной оплате
        deactivate provider
        scheduler -> postgres: Обновить TTL подписки (+ N дней)
        scheduler -> postgres: Записать лог успешной транзакции
        deactivate postgres
        scheduler -> notifications: Уведомление об успешном автопродлении
    end
else auto-renewal=False
    scheduler -> auth: Изменение роли пользователя на Default
    deactivate auth
    scheduler -> notifications: Уведомление об закончившейся подписке
    deactivate notifications
end
deactivate scheduler
@enduml

