version: '3.5'
services:
  billing_psql:
    image: postgres:13.0-alpine
    env_file:
      - "config.env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - cinema
    restart: always

  billing_api:
    build: components/billing_api
    env_file:
      - config.env
    restart: always
    networks:
      - cinema


networks:
  cinema:
    external:
      name: cinema
volumes:
  postgres_data:
