@startuml ugc-watch-film
== Старт просмотра ==
autonumber
activate WebClient
WebClient -> Service: POST watch/<UUID:film_id>
activate Service
database Redis
note over Service: Проверка JWT токенов
alt #LightBlue Просмотр разрешен
        database Kafka
        activate Kafka
        Service -> Kafka: Запись события
        Kafka --> Service: Записано
        activate Redis
        Service -> Redis: Запись данных
        Redis --> Service: Записано
        Service -> WebClient: Запрос удовлетворен
        deactivate Redis
    else #Pink Пользователь не имеет доступ к фильму
        Service -> WebClient: Запрос отклонен
    end
deactivate Kafka
deactivate Service

== Дальнейший просмотр ==
WebClient -> Service: Новые данные о просмотре
activate Service
activate Kafka
Service -> Kafka: Запись события
Kafka --> Service: Записано
activate ETL
database ClickHouse
ETL -> Kafka: Запрос данных
Kafka -> ETL: Отдача данных
deactivate Kafka
ETL -> ETL: Трансформация данных
activate ClickHouse
ETL -> ClickHouse: Запись в ClickHouse
ClickHouse --> ETL: Успешно
deactivate ClickHouse
activate Redis
Service -> Redis: Перезапись последних данных
Redis --> Service: Записано
deactivate Redis
deactivate ETL
@enduml