"""subs

Revision ID: 26357a37e372
Revises:
Create Date: 2023-07-11 10:34:30.528595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26357a37e372"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions_tiers",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subscribe_id", sa.UUID(), nullable=False),
        sa.Column("duratation", sa.DateTime(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("discount_duratation", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("subscribe_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions_tiers")
    # ### end Alembic commands ###
