version: '3'
services:
  ugc:
    build: .
    ports:
      - 8001:8000
    env_file:
      - config.env
    restart: always
    volumes:
      - ./src:/opt/ugc/src
      
  ugc_redis:
    image: redis:7.0.9
    restart: always
    env_file:
      - config.env

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
  
  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ADVERTISED_HOST_NAME}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
    restart: always
    depends_on:
      - zookeeper
    
volumes:
  src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './src'