version: '3.5'

services:
      
  python:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/bench

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '.'


