name: linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: $${{ matrix.python-version }}
      - run: python -m pip install flake8
      - name: flake8
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@d8afa2cfb66dd3f982b1950429e652bc14d0d7d2
        with:
          linters: flake8
          run: flake8
      - run: python -m pip install isort
      - name: isort
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@d8afa2cfb66dd3f982b1950429e652bc14d0d7d2
        with:
          linters: isort
          run: isort --check --diff .
      - name: black
        uses: psf/black@stable