name: linters with notification

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install flake8
      - name: flake8
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@d8afa2cfb66dd3f982b1950429e652bc14d0d7d2
        with:
          linters: flake8
          run: flake8
      - run: python -m pip install isort
      - name: isort
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@d8afa2cfb66dd3f982b1950429e652bc14d0d7d2
        with:
          linters: isort
          run: isort --check --diff .
      - name: black
        uses: psf/black@stable

  notification:
    runs-on: ubuntu-latest
    needs: [linters]
    steps:
      - name: send telegram message on push\pull
        uses: appleboy/telegram-action@master
        if: ${{ job.status == 'success' }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал\изменил ${{ github.event_name }}:
            Сообщение: ${{ github.event.head_commit.message }}
            Статус: ${{ job.status  }}
            Ветка\Тэг: ${{ github.ref_type }}, ref: ${{ github.ref }}

            Коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            (Если это пулл)
            Пулл создан: ${{ github.event.pull_request.created_at }}
            Пулл обновлен: ${{ github.event.pull_request.updated_at }}

            Зайти в репозиторий: https://github.com/${{ github.repository }}
