name: linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push\pull
        uses: appleboy/telegram-action@master
        if: ${{ job.status == 'success' }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал\изменил ${{ github.event_name }}:
            Сообщение: ${{ github.event.head_commit.message }}
            Статус: ${{ job.status  }}
            Ветка\Тэг: ${{ github.ref_type }}, ref: ${{ github.ref }}

            Коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            (Если это пулл)
            Пулл создан: ${{ github.event.pull_request.created_at }}
            Пулл обновлен: ${{ github.event.pull_request.updated_at }}

            Зайти в репозиторий: https://github.com/${{ github.repository }}

