name: linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push\pull
        uses: appleboy/telegram-action@master
        if: ${{ job.status == 'success' }}
        with:
          to: ${{ secrets.SAVED_MESSAGES }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал ${{ github.event_name }}:
            Сообщение: ${{ github.event.head_commit.id }}  ╮(︶︿︶)╭
            Сообщение: ${{ github.event.head_commit.message }}
            
            Репозиторий: ${{ github.repository }}
            Статус: ${{ job.status  }}
            Ветка: ${{ github.ref_name }}
            Коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Время: ${{ github.event.pull_request.created_at }}
            Зайти в репозиторий: https://github.com/${{ github.repository }}

