name: linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push\pull
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.SAVED_MESSAGES }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал ${{ github.event_name }}:
            Сообщение: ${{ github.event.commits[0].message }}  ╮(︶︿︶)╭
            
            Репозиторий: ${{ github.repository }}
        
            Посмотреть: ${{ github.event.name }}: https://github.com/${{ github.repository }}/pull/${{github.sha}}
            ${{ github.action }}
            ${{ github.action_repository }}
            ${{ github.run_attempt }}
            ${{ github.workspace }}
            ${{ github.action_status }}
            Зайти в репозиторий: ${{ github }}

