name: linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push\pull
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.SAVED_MESSAGES }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал ${{ github.event_name }}:
            Сообщение: ${{ github.event.commits[0].message }}  ╮(︶︿︶)╭
            
            Репозиторий: ${{ github.repository }}
        
            Посмотреть: ${{ github.event.name }}: https://github.com/${{ github.repository }}/pull/${{github.sha}}
            Ветка: ${{ github.ref_name }}
            Статус: ${{ github.action_status }}
            ${{ github.event.pull_request.re }}
            ${{ github.event.pull_request.created_at }}
            ${{ github.event.pull_request.url }}
            ${{ github.event.commits.added.message }}
            ${{ github.event_path }}
            ${{ github.event.head_commit.message }}
            ${{ github.event.workflow_run.status[0] }}
            Зайти в репозиторий: https://github.com/${{ github.repository }}

